- Add support for scripted agg metrics: https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-metrics-scripted-metric-aggregation.html
- Change Script handling to not provide params when Map is empty.
This was causing:

org.elasticsearch.search.SearchParseException: init_script params are
not supported. Parameters for the init_script must be specified in the
params field on the scripted_metric aggregator not inside the
init_script object

- Update tests resources according to previous change