SubscriberFlushAfterTest: Fix compilation error
```
elastic4s/elastic4s-streams/src/test/scala/com/sksamuel/elastic4s/streams/SubscriberFlushAfterTest.scala:90: type mismatch;
[error]  found   : _$1(in value s)
[error]  required: (some other)_$1(in value s)
[error]               remaining.take(1).foreach(s.onNext)
[error]                                           ^
```