circe: Fix compilation error for Scala 2.11 due to circe upgrade
```
elastic4s/elastic4s-circe/src/main/scala/com/sksamuel/elastic4s/circe/package.scala:40: value getOrElse is not a member of Either[io.circe.Error,T]
 possible cause: maybe a semicolon is missing before `value getOrElse'?
       .getOrElse(throw new IllegalArgumentException(s"Unable to parse ${hit.sourceAsString}"))
        ^
```

The `decode` method probably returned an `Option` in the former version, but
returns an `Either[Error, T]` now -- but `getOrElse` only exists in Scala 2.12
for `Either`.